# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2440ba031e21263bf11dcaf370e4bab5cbda9eca6e366f44b4a5c24e77e2d99447db9ba02c4d55cb68ddc58ba213b3bed0afe84e0de13aa799652801f6c01b74

test:
  secret_key_base: b5d48472a68cc9ed2e3a2bb8b483c2e36a20e1ea69b9bec578d9edcc95ec8000953f739c057524788956c3c568e63cb5d8aee10dbd86172c6a913dd6d699fca4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
